#fetch admin name,admin id,dept
SELECT E.EMPNAME,E.EMPID,D.DEPTNAME FROM EMPLOYEE E JOIN DEPT D ON D.DEPTID=E.DEPTID WHERE E.EMPID='E00';

#create user:
INSERT INTO EMPLOYEE VALUES
('F01','D01','E01','A','ASSISTANT PROFESSOR','1','A@XYZ.COM',1234567890);

#edit notesheet
NOTEID COLUMN: SELECT NOTEID FROM NOTESHEET;
VIEW NOTESHEET COLUMN: STATUS :SELECT A.NOTEID,A.APROVEDBY,E.DESIGNATION FROM APPROVED A,EMPLOYEE E WHERE E.EMPID=A.APROVEDBY;
SAVE: COMMIT COMMAND

#VIEW NOTESHEET:
NOTEID COLUMN: SELECT NOTEID FROM NOTESHEET;
VIEW NOTESHEET COLUMN: STATUS :SELECT A.NOTEID,A.APROVEDBY,E.DESIGNATION FROM APPROVED A,EMPLOYEE E WHERE E.EMPID=A.APROVEDBY;

#CREATE FACULTY:
INSERT INTO FACULTY VALUES('F00','ADMIN');

#CREATE DEPARTMENT:
INSERT INTO DEPT VALUES('F01','D01','CSE');

#VIEW FACULTY: SELECT * FROM FACULTY;

#VIEW DEPT: SELECT D.FID,F.FNAME,D.DEPTID,D.DEPTNAME FROM DEPT D JOIN FACULTY F WHERE F.FID=D.FID;
